global using FunctionalBlog.Application.Articles;
global using FunctionalBlog.Application.Identity;
global using FunctionalBlog.Application.Images;
global using FunctionalBlog.Application.Pages;
global using FunctionalBlog.Application.Recipes;
global using FunctionalBlog.Application.Roles;
global using FunctionalBlog.Application.Search;
global using FunctionalBlog.Application.Translations;
global using FunctionalBlog.Articles;
global using FunctionalBlog.DataAccess.Identity;
global using FunctionalBlog.DataAccess.Images;
global using FunctionalBlog.DataAccess.Pages;
global using FunctionalBlog.DataAccess.Sqlite;
global using FunctionalBlog.DataAccess.Translations;
global using FunctionalBlog.Domain.Articles;
global using FunctionalBlog.Domain.Identity;
global using FunctionalBlog.Domain.Images;
global using FunctionalBlog.Domain.Pages;
global using FunctionalBlog.Domain.Recipes;
global using FunctionalBlog.Domain.Roles;
global using FunctionalBlog.Domain.Translations;
global using FunctionalBlog.Identity;
global using FunctionalBlog.Images;
global using FunctionalBlog.Ingredients;
global using FunctionalBlog.Pages;
global using FunctionalBlog.Recipes;
global using FunctionalBlog.Roles;
global using FunctionalBlog.Translations;
global using static FunctionalBlog.Domain.Recipes.Unit;
global using App = FunctionalBlog.Pipeline.App<FunctionalBlog.Env, FunctionalBlog.Request, FunctionalBlog.Response>;
global using Functional = FunctionalBlog.Pipeline.Functional;
global using Middleware = FunctionalBlog.Pipeline.Middleware<FunctionalBlog.Env, FunctionalBlog.Request, FunctionalBlog.Response>;
