namespace FunctionalBlog;

public static class Routes
{
    public static RouteTable Build() => RouteTable.Empty
        .Get("/search/quick", Search.SearchHandlers.Quick)
        .Get("/search", Search.SearchHandlers.Search)
        .Get("/tag/{slug}", p => TagHandlers.Show(p[0]))
        .Get("/styles.css", StaticHandlers.Styles)
        .Get("/htmx.min.js", StaticHandlers.HtmxScript)
        .Get("/combobox-keys.js", StaticHandlers.ComboboxKeysScript)
        .Get("/confirm-delete.js", StaticHandlers.ConfirmDeleteScript)
        .Get("/autofocus-swap.js", StaticHandlers.AutofocusSwapScript)
        .Get("/favicon.ico", StaticHandlers.FaviconIco)
        .Get("/favicon.png", StaticHandlers.FaviconPng)
        .Get("/fonts/{file}", p => StaticHandlers.Font(p[0]))
        .Get("/assets/{file}", p => StaticHandlers.Asset(p[0]))
        .Get("/", BlogHandlers.Index)
        .Get("/register", AuthHandlers.NewRegisterForm)
        .Post("/register", AuthHandlers.Register)
        .Get("/login", AuthHandlers.NewLoginForm)
        .Post("/login", AuthHandlers.Login)
        .Post("/logout", Auth.RequireAuth(AuthHandlers.Logout))
        .Get("/password-reset", AuthHandlers.NewPasswordResetForm)
        .Post("/password-reset", AuthHandlers.RequestPasswordReset)
        .Get("/password-reset/confirm", AuthHandlers.NewPasswordResetConfirmForm)
        .Post("/password-reset/confirm", AuthHandlers.ConfirmPasswordReset)
        .Get("/users", Auth.RequireAuth(UsersHandlers.Index))
        .Get("/settings", Auth.RequireAuth(UserSettingsHandlers.Settings))
        .Post("/settings/password", Auth.RequireAuth(UserSettingsHandlers.ChangePassword))
        .Post("/settings/avatar", Auth.RequireAuth(UserSettingsHandlers.UpdateAvatar))
        .Post("/lang", TranslationHandlers.SetLanguage)
        .Post("/theme", ThemeHandlers.SetTheme)
        .Get("/articles/new", Auth.RequirePermission<Create>(new ArticleResource(), BlogHandlers.NewArticleForm))
        .Post("/articles", Auth.RequirePermission<Create>(new ArticleResource(), BlogHandlers.CreateArticle))
        .Get("/articles/{id}/edit", p => Auth.RequirePermission<Edit>(new ArticleResource(), BlogHandlers.EditArticleForm(new ArticleId(int.Parse(p[0])))))
        .Post("/articles/{id}/delete", p => Auth.RequirePermission<Delete>(new ArticleResource(), BlogHandlers.DeleteArticle(new ArticleId(int.Parse(p[0])))))
        .Post("/articles/{id}", p => Auth.RequirePermission<Edit>(new ArticleResource(), BlogHandlers.UpdateArticle(new ArticleId(int.Parse(p[0])))))
        .Get("/articles/{slug}", p => SlugDispatch.Resolve(SlugEntityType.Article, p[0], id => BlogHandlers.ShowArticle(new ArticleId(id))))
        .Get("/images", Auth.RequirePermission<Manage>(new ImageResource(), ImageHandlers.Library))
        .Post("/images", Auth.RequirePermission<Create>(new ImageResource(), ImageHandlers.Upload))
        .Post("/images/{id}/delete", p => Auth.RequirePermission<Delete>(new ImageResource(), ImageHandlers.Delete(new ImageId(int.Parse(p[0])))))
        .Get("/images/{id}", p => ImageHandlers.Serve(new ImageId(int.Parse(p[0]))))
        .Get("/pages", PageHandlers.Index)
        .Get("/pages/new", Auth.RequirePermission<Create>(new PageResource(), PageHandlers.NewPageForm))
        .Post("/pages", Auth.RequirePermission<Create>(new PageResource(), PageHandlers.CreatePage))
        .Get("/pages/{id}/edit", p => Auth.RequirePermission<Edit>(new PageResource(), PageHandlers.EditPageForm(new PageId(int.Parse(p[0])))))
        .Post("/pages/{id}/delete", p => Auth.RequirePermission<Delete>(new PageResource(), PageHandlers.DeletePage(new PageId(int.Parse(p[0])))))
        .Post("/pages/{id}", p => Auth.RequirePermission<Edit>(new PageResource(), PageHandlers.UpdatePage(new PageId(int.Parse(p[0])))))
        .Get("/pages/{slug}", p => SlugDispatch.Resolve(SlugEntityType.Page, p[0], id => PageHandlers.ShowPage(new PageId(id))))
        .Get("/recipes/new", Auth.RequirePermission<Create>(new RecipeResource(), RecipeHandlers.NewRecipeForm))
        .Get("/recipes", RecipeHandlers.Index)
        .Post("/recipes", Auth.RequirePermission<Create>(new RecipeResource(), RecipeHandlers.CreateRecipe))
        .Post("/recipes/form/ingredients", Auth.RequirePermission<Create>(new RecipeResource(), RecipeHandlers.IngredientsSection))
        .Post("/recipes/form/ingredient-search", Auth.RequirePermission<Create>(new RecipeResource(), RecipeHandlers.IngredientSearch))
        .Post("/recipes/form/ingredient-select", Auth.RequirePermission<Create>(new RecipeResource(), RecipeHandlers.IngredientSelect))
        .Post("/recipes/form/steps", Auth.RequirePermission<Create>(new RecipeResource(), RecipeHandlers.StepsSection))
        .Get("/recipes/{id}/edit", p => Auth.RequirePermission<Edit>(new RecipeResource(), RecipeHandlers.EditRecipeForm(new RecipeId(int.Parse(p[0])))))
        .Post("/recipes/{id}/delete", p => Auth.RequirePermission<Delete>(new RecipeResource(), RecipeHandlers.DeleteRecipe(new RecipeId(int.Parse(p[0])))))
        .Post("/recipes/{id}", p => Auth.RequirePermission<Edit>(new RecipeResource(), RecipeHandlers.UpdateRecipe(new RecipeId(int.Parse(p[0])))))
        .Get("/recipes/{id}/pdf", p => RecipePdfHandlers.Download(new RecipeId(int.Parse(p[0]))))
        .Get("/recipes/{slug}", p => SlugDispatch.Resolve(SlugEntityType.Recipe, p[0], id => RecipeHandlers.ShowRecipe(new RecipeId(id))))
        .Get("/ingredients", IngredientHandlers.Index)
        .Get("/ingredients/{slug}", p => SlugDispatch.Resolve(SlugEntityType.Ingredient, p[0], id => IngredientHandlers.Show(new IngredientId(id))))
        .Get("/admin", Auth.RequireAuth(AdminDashboardHandlers.Dashboard))
        .Get("/admin/ingredients/new", Auth.RequirePermission<Create>(new IngredientResource(), AdminIngredientHandlers.NewForm))
        .Get("/admin/ingredients", Auth.RequirePermission<Manage>(new IngredientResource(), AdminIngredientHandlers.List))
        .Post("/admin/ingredients", Auth.RequirePermission<Create>(new IngredientResource(), AdminIngredientHandlers.Create))
        .Get("/admin/ingredients/{id}/edit", p => Auth.RequirePermission<Edit>(new IngredientResource(), AdminIngredientHandlers.EditForm(new IngredientId(int.Parse(p[0])))))
        .Post("/admin/ingredients/{id}/delete", p => Auth.RequirePermission<Manage>(new IngredientResource(), AdminIngredientHandlers.Delete(new IngredientId(int.Parse(p[0])))))
        .Post("/admin/ingredients/{id}", p => Auth.RequirePermission<Edit>(new IngredientResource(), AdminIngredientHandlers.Update(new IngredientId(int.Parse(p[0])))))
        .Get("/admin/units", Auth.RequirePermission<Manage>(new UnitResource(), AdminUnitHandlers.List))
        .Get("/admin/units/new-row", Auth.RequirePermission<Create>(new UnitResource(), AdminUnitHandlers.NewRow))
        .Get("/admin/units/cancel-new", Auth.RequirePermission<Create>(new UnitResource(), AdminUnitHandlers.CancelNew))
        .Post("/admin/units", Auth.RequirePermission<Create>(new UnitResource(), AdminUnitHandlers.Create))
        .Get("/admin/units/{id}/edit-row", p => Auth.RequirePermission<Edit>(new UnitResource(), AdminUnitHandlers.EditRow(new UnitId(int.Parse(p[0])))))
        .Get("/admin/units/{id}/row", p => Auth.RequirePermission<Edit>(new UnitResource(), AdminUnitHandlers.Row(new UnitId(int.Parse(p[0])))))
        .Post("/admin/units/{id}/delete", p => Auth.RequirePermission<Manage>(new UnitResource(), AdminUnitHandlers.Delete(new UnitId(int.Parse(p[0])))))
        .Post("/admin/units/{id}", p => Auth.RequirePermission<Edit>(new UnitResource(), AdminUnitHandlers.Update(new UnitId(int.Parse(p[0])))))
        .Get("/admin/search", Auth.RequirePermission<Manage>(new SearchResource(), AdminSearchHandlers.Status))
        .Post("/admin/search/rebuild", Auth.RequirePermission<Manage>(new SearchResource(), AdminSearchHandlers.Rebuild))
        .Get("/admin/users", Auth.RequirePermission<Manage>(new UserResource(), AdminHandlers.UserList))
        .Get("/admin/users/{id}", p => Auth.RequirePermission<Manage>(new UserResource(), AdminHandlers.UserDetail(int.Parse(p[0]))))
        .Post("/admin/users/{id}/roles", p => Auth.RequirePermission<Manage>(new UserResource(), AdminHandlers.UpdateUserRoles(int.Parse(p[0]))))
        .Get("/admin/roles/new", Auth.RequirePermission<Create>(new RoleResource(), AdminHandlers.NewRoleForm))
        .Get("/admin/roles", Auth.RequirePermission<Manage>(new RoleResource(), AdminHandlers.RoleList))
        .Post("/admin/roles", Auth.RequirePermission<Create>(new RoleResource(), AdminHandlers.CreateRole))
        .Get("/admin/roles/{id}", p => Auth.RequirePermission<Manage>(new RoleResource(), AdminHandlers.RoleDetail(int.Parse(p[0]))))
        .Post("/admin/roles/{id}/rules", p => Auth.RequirePermission<Manage>(new RuleResource(), AdminHandlers.AddRule(int.Parse(p[0]))))
        .Post("/admin/roles/{id}/rules/delete", p => Auth.RequirePermission<Manage>(new RuleResource(), AdminHandlers.DeleteRule(int.Parse(p[0]))))
        .Post("/admin/roles/{id}/delete", p => Auth.RequirePermission<Manage>(new RoleResource(), AdminHandlers.DeleteRole(int.Parse(p[0]))))
        .Get("/admin/translations/export.json", Auth.RequirePermission<Manage>(new UserResource(), TranslationHandlers.Export))
        .Get("/admin/translations", Auth.RequirePermission<Manage>(new UserResource(), TranslationHandlers.List))
        .Post("/admin/translations/{key}/{lang}", p => Auth.RequirePermission<Manage>(new UserResource(), TranslationHandlers.Save(p[0], p[1])));
}
