namespace FunctionalBlog;

public static class Routes
{
    public static RouteTable Build() => RouteTable.Empty
        .Get("/styles.css", StaticHandlers.Styles)
        .Get("/htmx.min.js", StaticHandlers.HtmxScript)
        .Get("/", BlogHandlers.Index)
        .Get("/register", AuthHandlers.NewRegisterForm)
        .Post("/register", AuthHandlers.Register)
        .Get("/login", AuthHandlers.NewLoginForm)
        .Post("/login", AuthHandlers.Login)
        .Post("/logout", Auth.RequireAuth(AuthHandlers.Logout))
        .Get("/password-reset", AuthHandlers.NewPasswordResetForm)
        .Post("/password-reset", AuthHandlers.RequestPasswordReset)
        .Get("/password-reset/confirm", AuthHandlers.NewPasswordResetConfirmForm)
        .Post("/password-reset/confirm", AuthHandlers.ConfirmPasswordReset)
        .Get("/settings", Auth.RequireAuth(UserSettingsHandlers.Settings))
        .Post("/settings/password", Auth.RequireAuth(UserSettingsHandlers.ChangePassword))
        .Post("/lang", TranslationHandlers.SetLanguage)
        .Get("/articles/new", Auth.RequirePermission<Create>(new ArticleResource(), BlogHandlers.NewArticleForm))
        .Post("/articles", Auth.RequirePermission<Create>(new ArticleResource(), BlogHandlers.CreateArticle))
        .Get("/articles/{id}/edit", p => Auth.RequirePermission<Edit>(new ArticleResource(), BlogHandlers.EditArticleForm(new ArticleId(int.Parse(p[0])))))
        .Post("/articles/{id}/delete", p => Auth.RequirePermission<Delete>(new ArticleResource(), BlogHandlers.DeleteArticle(new ArticleId(int.Parse(p[0])))))
        .Post("/articles/{id}", p => Auth.RequirePermission<Edit>(new ArticleResource(), BlogHandlers.UpdateArticle(new ArticleId(int.Parse(p[0])))))
        .Get("/articles/{id}", p => BlogHandlers.ShowArticle(new ArticleId(int.Parse(p[0]))))
        .Get("/recipes/new", Auth.RequirePermission<Create>(new RecipeResource(), RecipeHandlers.NewRecipeForm))
        .Get("/recipes", RecipeHandlers.Index)
        .Post("/recipes", Auth.RequirePermission<Create>(new RecipeResource(), RecipeHandlers.CreateRecipe))
        .Post("/recipes/form/ingredients", Auth.RequirePermission<Create>(new RecipeResource(), RecipeHandlers.IngredientsSection))
        .Post("/recipes/form/steps", Auth.RequirePermission<Create>(new RecipeResource(), RecipeHandlers.StepsSection))
        .Get("/recipes/{id}/edit", p => Auth.RequirePermission<Edit>(new RecipeResource(), RecipeHandlers.EditRecipeForm(new RecipeId(int.Parse(p[0])))))
        .Post("/recipes/{id}/delete", p => Auth.RequirePermission<Delete>(new RecipeResource(), RecipeHandlers.DeleteRecipe(new RecipeId(int.Parse(p[0])))))
        .Post("/recipes/{id}", p => Auth.RequirePermission<Edit>(new RecipeResource(), RecipeHandlers.UpdateRecipe(new RecipeId(int.Parse(p[0])))))
        .Get("/recipes/{id}", p => RecipeHandlers.ShowRecipe(new RecipeId(int.Parse(p[0]))))
        .Get("/admin/ingredients/new", Auth.RequirePermission<Create>(new IngredientResource(), AdminIngredientHandlers.NewForm))
        .Get("/admin/ingredients", Auth.RequirePermission<Manage>(new IngredientResource(), AdminIngredientHandlers.List))
        .Post("/admin/ingredients", Auth.RequirePermission<Create>(new IngredientResource(), AdminIngredientHandlers.Create))
        .Get("/admin/ingredients/{id}/edit", p => Auth.RequirePermission<Edit>(new IngredientResource(), AdminIngredientHandlers.EditForm(new IngredientId(int.Parse(p[0])))))
        .Post("/admin/ingredients/{id}/delete", p => Auth.RequirePermission<Manage>(new IngredientResource(), AdminIngredientHandlers.Delete(new IngredientId(int.Parse(p[0])))))
        .Post("/admin/ingredients/{id}", p => Auth.RequirePermission<Edit>(new IngredientResource(), AdminIngredientHandlers.Update(new IngredientId(int.Parse(p[0])))))
        .Get("/admin/users", Auth.RequirePermission<Manage>(new UserResource(), AdminHandlers.UserList))
        .Get("/admin/users/{id}", p => Auth.RequirePermission<Manage>(new UserResource(), AdminHandlers.UserDetail(int.Parse(p[0]))))
        .Post("/admin/users/{id}/roles", p => Auth.RequirePermission<Manage>(new UserResource(), AdminHandlers.UpdateUserRoles(int.Parse(p[0]))))
        .Get("/admin/roles/new", Auth.RequirePermission<Create>(new RoleResource(), AdminHandlers.NewRoleForm))
        .Get("/admin/roles", Auth.RequirePermission<Manage>(new RoleResource(), AdminHandlers.RoleList))
        .Post("/admin/roles", Auth.RequirePermission<Create>(new RoleResource(), AdminHandlers.CreateRole))
        .Get("/admin/roles/{id}", p => Auth.RequirePermission<Manage>(new RoleResource(), AdminHandlers.RoleDetail(int.Parse(p[0]))))
        .Post("/admin/roles/{id}/rules", p => Auth.RequirePermission<Manage>(new RuleResource(), AdminHandlers.AddRule(int.Parse(p[0]))))
        .Post("/admin/roles/{id}/delete", p => Auth.RequirePermission<Manage>(new RoleResource(), AdminHandlers.DeleteRole(int.Parse(p[0]))))
        .Get("/admin/translations/export.json", Auth.RequirePermission<Manage>(new UserResource(), TranslationHandlers.Export))
        .Get("/admin/translations", Auth.RequirePermission<Manage>(new UserResource(), TranslationHandlers.List))
        .Post("/admin/translations/{key}/{lang}", p => Auth.RequirePermission<Manage>(new UserResource(), TranslationHandlers.Save(p[0], p[1])));
}
