global using FunctionalBlog.Application.Articles;
global using FunctionalBlog.Application.Pages;
global using FunctionalBlog.Application.Recipes;
global using FunctionalBlog.Application.Tags;
global using FunctionalBlog.Domain.Articles;
global using FunctionalBlog.Domain.Identity;
global using FunctionalBlog.Domain.Images;
global using FunctionalBlog.Domain.Pages;
global using FunctionalBlog.Domain.Recipes;
global using FunctionalBlog.Domain.Roles;
global using FunctionalBlog.Domain.Slugs;
global using FunctionalBlog.Domain.Tags;
global using FunctionalBlog.Domain.Translations;
global using Unit = FunctionalBlog.Domain.Recipes.Unit;
